name: Auto deploy per day

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 18 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect GitHub workflow with repository
        uses: actions/checkout@v2
      - name: Install TypeScript
        run: npm ci
      - run: npm run hospital
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v19.0.1+1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'
