name: Setup rich-menu per push

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connect GitHub workflow with repository
        uses: actions/checkout@v2
      - name: Install TypeScript
        run: npm ci
      - name: Setup LINE rich menu
        run: npm run rich-menu
        env:
          CHANNEL_ACCESS_TOKEN: ${{ secrets.CHANNEL_ACCESS_TOKEN }}
          CHANNEL_SECRET: ${{ secrets.CHANNEL_SECRET }}
